# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_func', '0001_initial'),
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='DevModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('i', 'input'), ('o', 'output')], max_length=1)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_func.FeatureFunc')),
                ('mod', models.ManyToManyField(to='dev_model.DevModel')),
            ],
        ),
        migrations.AddField(
            model_name='dev',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_model.DevModel'),
        ),
    ]
