# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='dev',
            field=models.ManyToManyField(to='dev_model.Dev'),
        ),
    ]
