# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0002_feature_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='cate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_model.Category'),
        ),
    ]
