# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0004_auto_20160904_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='type',
            field=models.CharField(choices=[('i', 'input'), ('o', 'output')], default='i', max_length=1),
            preserve_default=False,
        ),
    ]
