# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0005_dev_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_func.FeatureFunc'),
        ),
    ]
