# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0006_auto_20160906_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltag',
            name='mod',
            field=models.ManyToManyField(blank=True, to='dev_model.DevModel'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='dev',
            field=models.ManyToManyField(blank=True, to='dev_model.Dev'),
        ),
    ]
