# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_model', '0007_auto_20160906_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='dev',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_model.Dev'),
        ),
    ]
